### ISSUE TITLE
Resource incorrectly sorts versions

### ISSUE THREAD

**Issue by mymasse** [tlwr/registry-tag-resource#3]
We use this resource to fetch new versions of the minio/minio docker image, we use the following resource configuration:

```yaml
- name: minio-release
  type: registry-tag
  check_every: 24h
  icon: tag
  source:
    uri: https://hub.docker.com/v2/repositories/minio/minio
    regexp: ^RELEASE\.\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}Z$
    pages: 25
    tags_per_page: 25
```

However it currently fetched the releases in this order (only the last 5 shown)

* RELEASE.2021-07-08T01-15-01Z
* RELEASE.2021-07-15T22-27-34Z
* RELEASE.2021-07-12T02-44-53Z
* RELEASE-2021-07-08T19-43-25Z
* RELEASE-2021-06-17T00-10-46Z

I looked at the code and the resource doesn't seem to apply any sorting in the request or after fetching the tag list. Sorting is only applied if using semver (which we can't in our case). 

Should the list_tags query docker hub with a sort parameter or could the resource have a parameter (when not semver) to request sorting by name?
