### ISSUE TITLE
Resource filters out valid semver version when prefixed

### ISSUE THREAD

**Issue by mymasse** [tlwr/registry-tag-resource#4]
Trying to pull minio/console releases with the following config and I get nothing

```yaml
- name: minio-console-release
  type: registry-tag
  check_every: 24h
  icon: tag
  source:
    uri: https://hub.docker.com/v2/repositories/minio/console
    regexp: ^v\d+\.\d+\.\d+$
    pages: 10
    tags_per_page: 25
    semver:
      prefix: v
      matcher: '>= 0.8.0'
```

Looking at the code (I'm no Ruby expert) I think the problem is here: https://github.com/tlwr/registry-tag-resource/blob/85b5ad843866ca9112597e091513b58d8a709453/bin/check#L68

Probably should have a `#` when comparing with line https://github.com/tlwr/registry-tag-resource/blob/85b5ad843866ca9112597e091513b58d8a709453/bin/check#L78

**Comment by mymasse** [comment]
Also having issues with the following which seems related to pre-releases/build in the semver

```yaml
  - name: nexus
    update_dev: true
    update_prod: true
    type: tfvars
    name_in_tfvars: nexus_version
    release_notes:
      url: https://help.sonatype.com/repomanager3/release-notes
      append_version: false
    resource:
      type: registry-tag
      uri: https://hub.docker.com/v2/repositories/sonatype/nexus3
      extra_source:
        regexp: ^\d+\.\d+\.\d+$
        pages: 5
        semver:
          matcher: ">= 3"
```

Which returns an error:

```
/usr/local/bundle/gems/semantic-1.6.1/lib/semantic/version.rb:15:in `initialize': 3.9.0-01 is not a valid SemVer Version (http://semver.org) (ArgumentError)
	from /opt/resource/check:68:in `new'
	from /opt/resource/check:68:in `block in <main>'
	from /opt/resource/check:67:in `select'
	from /opt/resource/check:67:in `<main>'
```
